[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git          # root of the project
    | \.venv
    | \.env
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py 
                     # the root of the project
)
'''